name: 'typocop'
description: 'GitHub action comments on PRs with typos or approvals'
author: "Datpmt <datpmt.2k@gmail.com>"
repository: "https://github.com/datpmt/typocop"
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  pull_request_id:
    description: 'Pull Request ID'
    required: true
  github_base_ref:
    description: 'GitHub Base Ref'
    required: true
  setting:
    description: 'Path to the custom setting.yml file for Typocop'
    required: false
    default: .github/typocop/setting.yml

runs:
  using: 'composite'
  steps:
    - name: Check for Gemfile and Add Typocop if Missing
      id: check_gemfile
      run: |
        if [ -f Gemfile ]; then
          if ! grep -q "gem 'typocop'" Gemfile; then
            echo "gem 'typocop'" >> Gemfile
          fi
        else
          echo "source 'https://rubygems.org'" > Gemfile
          echo "gem 'typocop'" >> Gemfile
        fi
      shell: bash

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.1'
        bundler-cache: true

    - name: Run Typocop
      run: |
        bundle exec typocop execute --config ${{ inputs.setting }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PULL_REQUEST_ID: ${{ inputs.pull_request_id }}
        GITHUB_BASE_REF: ${{ inputs.github_base_ref }}
      shell: bash
