name: 'typocop'
description: 'GitHub action comments on PRs with typos or approvals'
author: "Datpmt <datpmt.2k@gmail.com>"
repository: "https://github.com/datpmt/typocop"
branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  github_token:
    description: 'GitHub Token'
    required: true
  pull_request_id:
    description: 'Pull Request ID'
    required: true
  github_base_ref:
    description: 'GitHub Base Ref'
    required: true
  setting:
    description: 'Path to the custom setting.yml file for Typocop'
    required: false
    default: .github/typocop/setting.yml

runs:
  using: 'composite'
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    # Cache Ruby gems to speed up gem installation
    - name: Cache Ruby gems
      uses: actions/cache@v3
      with:
        path: |
          ~/.gem
          vendor/bundle
        key: gem-cache-${{ runner.os }}-ruby-${{ hashFiles('Gemfile.lock') }}
        restore-keys: |
          gem-cache-${{ runner.os }}-ruby-

    # Install Typocop
    - name: Install Typocop
      run: |
        gem install typocop
      shell: bash

    # Run Typocop
    - name: Run Typocop
      run: |
        typocop execute --config ${{ inputs.setting }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        PULL_REQUEST_ID: ${{ inputs.pull_request_id }}
        GITHUB_BASE_REF: ${{ inputs.github_base_ref }}
      shell: bash
